name: Build Windows EXE

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with MinGW
        shell: bash
        run: |
          g++ -std=c++17 -O2 -municode -mwindows main.cpp -o PPSSPP_Mouse_Camera_V2.exe -luser32 -lshell32

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PPSSPP_Mouse_Camera_V2
          path: PPSSPP_Mouse_Camera_V2.exe
